# Tags: 3.5-20211109-windowsservercore-ltsc2022, 3.5-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/framework/aspnet:3.5-20211109-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/framework/aspnet:3.5-windowsservercore-ltsc2022
